Repository AY2223S1-CS2103T-W12-2/tp, pull requests merged in 2022-10, with the labels that each got.

#34 Update index page of SectresBook website
  docs/index.md
Labels: priority.Medium

#27 Update README.md
  README.md
Labels: priority.Medium

#31 Update User Guide Ryan: Locating persons by tag
  docs/UserGuide.md
  docs/images/findTagFinance.png
Labels: priority.High

#35 Updated User stories in DG
  docs/DeveloperGuide.md
Labels: priority.High

#38 Updates Product Scope, NFR and Glossary
  docs/DeveloperGuide.md
Labels: priority.High

#37 Reformat UG
  docs/UserGuide.md
Labels: priority.High

#43 Update developer guide with use cases
  docs/DeveloperGuide.md
Labels: priority.High

#44 Add Zhong Wei Skeletal PPP
  docs/team/czhongwei.md
Labels: priority.High

#45 Updates AboutUs.md to Link to rui-han-crh's PPP
  docs/AboutUs.md
Labels: priority.Medium

#55 Restructure tag, Find by tag
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/person/TagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/exceptions/DuplicateTagException.java
  src/main/java/seedu/address/model/tag/exceptions/TagNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/TagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#53 Add find by number
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
Labels: type.Story, priority.High

#50 Adds the Loans Property to Person Objects
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#52 Change Parser Command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: enhancement, priority.High

#57 Update delete command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: priority.High

#54 Added Notes
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/ListNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/note/Content.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/NoteBook.java
  src/main/java/seedu/address/model/note/Title.java
  src/main/java/seedu/address/model/note/exceptions/DuplicateNoteException.java
  src/main/java/seedu/address/model/note/exceptions/NoteNotFoundException.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#61 Refactors Code by Changing Insertion Point of New Tags
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/DeepCopyable.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/ShallowCopyable.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/tag/UniqueTagList.java
  src/main/java/seedu/address/model/tag/UniqueTagMapping.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/LoanTest.java
  src/test/java/seedu/address/model/person/NameTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/model/tag/UniqueTagListTest.java
  src/test/java/seedu/address/model/tag/UniqueTagMappingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: enhancement, priority.Medium

#65 Update findTag UG and findTag command word - Ryan
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
Labels: documentation

#64 updated UG with new note commands
  docs/UserGuide.md
Labels: documentation

#66 Update delete command in UG to reflect changes in v1.2
  docs/UserGuide.md
Labels: documentation

#60 Add find by number
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Story, priority.High

#68 Update UserGuide.md to include changes to find command
  docs/UserGuide.md
  docs/images/find86result.png
  docs/images/findlidResult.png
Labels: type.Story, priority.High

#69 Added filteredList for notes(for gui)
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#70 Update v1.2 dg
  docs/DeveloperGuide.md
  docs/diagrams/AddNoteSequenceDiagram.puml
  docs/diagrams/DeleteNoteSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/AddNoteSequenceDiagram.png
  docs/images/DeleteNoteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.High

#71 Updates UIClassDiagram and Adds EditSequenceDiagram
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation, priority.High

#73 Update DG findTag - Ryan
  docs/DeveloperGuide.md
  docs/diagrams/FindTagSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/FindTagSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ryanczx.png
Labels: documentation, priority.High

#81 Add notes edit find
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/FindNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindNoteCommandParser.java
  src/main/java/seedu/address/model/note/TitleContainsKeywordsPredicate.java
Labels: enhancement, priority.High

#78 Add Find command for DG and its sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/FindCommandSequence.puml
  docs/images/FindCommandSequence.png
Labels: type.Story, priority.High

#79 Update delete command implementation to simplify the parser
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
Labels: enhancement, priority.High

#80 Update the developer guide with Delete command implementation with name.
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceWithNameDiagram.puml
  docs/images/DeleteSequenceWithNameDiagram.png
Labels: documentation

#84 DG Edit Command Update
  docs/DeveloperGuide.md
  docs/diagrams/NoteClassDiagram.puml
  docs/diagrams/PersonClassDiagram.puml
  docs/images/NoteClassDiagram.png
  docs/images/PersonClassDiagram.png
Labels: documentation, priority.Medium

#85 findTag for notes
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/note/Note.java
  src/main/java/seedu/address/model/note/NoteBook.java
  src/main/java/seedu/address/model/note/NoteTagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonTagsContainsKeywordsPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedNote.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
  src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
  src/test/java/seedu/address/model/note/NoteTagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonTagsContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/testutil/NoteBuilder.java
Labels: enhancement, priority.High

#86 Change all usage of prefixes to new set of prefixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/Prefix.java
Labels: documentation, type.Story, priority.Medium

#90 Updated UserGuide for V1.3
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/StringUtil.java
Labels: documentation, priority.Medium

#93 Update user guide with editLoan command and command summary.
  docs/UserGuide.md
Labels: documentation, priority.High

#98 Add Birthday field to Person
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthday.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/BirthdayTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, type.Story, priority.High

#97 Change all n_tag/ to tag/ and fix DG broken note
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddNoteCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditNoteCommandParser.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindTagCommandTest.java
Labels: documentation

#100 Add testcases for notes, updated deleteNote/editNote implementation
  src/main/java/seedu/address/logic/commands/DeleteNoteCommand.java
  src/main/java/seedu/address/logic/commands/EditNoteCommand.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
  src/test/java/seedu/address/testutil/EditNoteDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalNotes.java
Labels: bug, documentation, enhancement, priority.High

#103 Amend CLI Control
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#101 Update user guide to align with editLoan command changes.
  docs/UserGuide.md
Labels: documentation

#174 Add screenshots ug - showNotes and hideNotes
  docs/images/hideNotes-after.png
  docs/images/hideNotes-before.png
  docs/images/showNotes-after.png
  docs/images/showNotes-before.png
Labels: documentation

#172 Update all screenshots in the UG
  docs/images/find86result.png
  docs/images/findAlexDavidResult.png
  docs/images/findTagFinance.png
Labels: documentation, type.DocumentationBug

#175 Update findTag Info
  docs/images/findTagFinance.png
  docs/images/findTagOperations.png
  src/main/java/seedu/address/logic/commands/FindTagCommand.java
Labels: documentation
