Repository AY2223S1-CS2103T-W12-2/tp, pull requests merged in 2022-11, with the labels that each got.

#178 Fix 2 images find86result.png and findAlexDavidResult.png
  docs/images/find86result.png
  docs/images/findAlexDavidResult.png
Labels: documentation

#182 [PATCH] Fixed javafx version and small typo in ug
  build.gradle
  docs/UserGuide.md
Labels: bug, documentation, severity.Medium, type.DocumentationBug

#179 [PATCH] Constraints Loan between Bounds, Fixes String Representation and Adds Tests
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditLoanCommand.java
  src/main/java/seedu/address/logic/commands/ListNoteCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditLoanCommandParser.java
  src/main/java/seedu/address/logic/parser/InspectCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Loan.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Reason.java
  src/main/java/seedu/address/model/person/exceptions/LoanOutOfBoundsException.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddNoteCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditLoanCommandTest.java
  src/test/java/seedu/address/logic/commands/ListNoteCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditLoanCommandParserTest.java
  src/test/java/seedu/address/model/person/LoanTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
Labels: severity.High, type.FunctionalityBug

#180 UG More Updates and Fixes
  docs/UserGuide.md
  docs/images/ResultsDisplay.png
  docs/images/findTagOperations.png
  docs/images/findTagOperationsFinance.png
Labels: documentation

#187 Update v.1.3 dg
  docs/DeveloperGuide.md
  docs/diagrams/EditNoteActivityDiagram.puml
  docs/diagrams/EditNoteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditNoteActivityDiagram.png
  docs/images/EditNoteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
Labels: documentation, priority.High

#177 Change VALIDATION_REGEX of Name
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/parser/EditLoanCommandParserTest.java
  src/test/java/seedu/address/model/person/NameTest.java
Labels: severity.High

#190 DG Update findTag
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/diagrams/FindTagSequenceDiagram.puml
  docs/images/FindTagSequenceDiagram.png
  docs/team/ryanczx.md
Labels: documentation

#191 Update v.1.3 ppp
  docs/AboutUs.md
  docs/team/pinran-j.md
Labels: documentation

#192 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#193 Edit DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/EditLoanSequenceDiagram.puml
  docs/images/EditLoanSequenceDiagram.png
Labels: documentation

#195 Add content to manual testing section
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation

#206 Updated PPP format
  docs/team/pinran-j.md
Labels: documentation

#208 Update pinran ppp fix
  docs/team/pinran-j.md
Labels: documentation
